### ISSUE TITLE
Map Service Property: Credits

### ISSUE THREAD

**Issue by bruce-tonkin** [bcgov/whse_2_agol#13]
If the property is configured in the config file, it generates and error in the build.
	"credits": "Province of British Columbia, {}".format(datetime.datetime.now().year)
This works without a problem.
"credits": "DataBC, Province of British Columbia"

**Comment by banders** [comment]
If the "credits" field is omitted in the config file, the python code will populate it with a default value which does include a dynamic year value: "Province of British Columbia, {YEAR}", but we do not currently support substitution strings within the config file itself.  The config file only supports static content.

Is it a requirement to also support substitution strings for config file properties?

**Comment by bruce-tonkin** [comment]
@banders   No, that is not critical.  I am happy with:
"credits": "DataBC, Province of British Columbia"

**Comment by banders** [comment]
Can we close this issue?

**Comment by bruce-tonkin** [comment]
Yes please.
