### ISSUE TITLE
Map Services: Use Lower case

### ISSUE THREAD

**Issue by bruce-tonkin** [bcgov/whse_2_agol#14]
All map services that are published should be in lower case eg:
whse/bcgw_pub_REG_LAND_AND_NATURAL_RESOURCE
to match our standards and all other map services.

**Comment by banders** [comment]
@bruce-tonkin I have made this change.

**Comment by bruce-tonkin** [comment]
I should have asked.  Could this change just be a matter of using lower case in the service-config-dlvr.json?

**Comment by banders** [comment]
I think it is better that we enforce the lowercase rule in python code.  It will result in process that is less susceptible to problems.

**Comment by bruce-tonkin** [comment]
Thanks @banders   I agree, however a lowercase schema name in the properties file should also be fine.
"schema": "WHSE_MINERAL_TENURE",

**Comment by banders** [comment]
The current process should still work if the schema is lowercase.

**Comment by bruce-tonkin** [comment]
Services have been deployed in lowercase.  So we can close this ticket.
