### ISSUE TITLE
Archive Folder for mxd's

### ISSUE THREAD

**Issue by bruce-tonkin** [bcgov/whse_2_agol#15]
Currently the app is writing archive mxd files to the mpcm folder.  Can this be changed to something other than the MPCM folder?
ie change
E:\sw_nt\jenkins\workspace\waops\MAXLS_build_publish>set ARCHIVE_DIR=E:\apps_data\userdata\mpcm\scripts\archive\DLVR\20201022 
to
\\alpheratz.dmz\e$\apps_data\ago_publish\managed_mxd or
\\alpheratz.dmz\e$\apps_data\ago_publish\published_mxd

**Comment by banders** [comment]
How about we move the archive to:
\alpheratz.dmz\e$\apps_data\ago_publish\archived_mxd
?

Can you create the folder?

**Comment by bruce-tonkin** [comment]
Looking a little deeper there are lots of files written to the MPCM folder.  Can the WHSE folder be used instead.
Change any references of 
\\alpheratz.dmz\e$\apps_data\userdata\mpcm
\\alpheratz.dmz\e$\apps_data\userdata\mpcm\scripts\ago_publish
to folder
\\alpheratz.dmz\e$\apps_data\userdata\whse

**Comment by bruce-tonkin** [comment]
Perfect.  Folder created: \\alpheratz.dmz\e$\apps_data\ago_publish\archived_mxd
