### ISSUE TITLE
ArcGIS server config file - 3 environments

### ISSUE THREAD

**Issue by mboulstr1** [bcgov/whse_2_agol#5]
Marion needs to produce config files for delivery

**Comment by banders** [comment]
I have split the service configuration into three separate files (one for each environment):

service-config-dlvr.json
service-config-test.json
service-config-prod.json

all are located in https://gogs.data.gov.bc.ca/waops/whse_2_agol/app/mxd/config/

@bruce-tonkin can you review the three files?  They are currently all duplicates of the original service-config.json file, which I think was prepared for production.  The dlvr and test versions will probably need to be adjusted.

**Comment by bruce-tonkin** [comment]
@banders   I have made changes to the delivery file, which is all we need for now.  See ticket #8 for more details.
