### ISSUE TITLE
Creation of TEMP folder on Alpheratz

### ISSUE THREAD

**Issue by mboulstr1** [bcgov/whse_2_agol#7]
Brock needs a spot other than the C: drive to place the mxd for publishing to the other environments from Alpheratz

**Comment by bruce-tonkin** [comment]
Currently all temp files are written to c:\windows\temp on server alpheratz.  We need to find a new location other than the c:\ drive

**Comment by banders** [comment]
We should double check that the temp folder is really needed for publication of services. I will investigate.

**Comment by banders** [comment]
I have confirmed that the publish process does require a temp folder, but I have changed it from 
c:\windows\temp to the jenkins workspace folder, which I think gets automatically cleaned up by Jenkins after a job runs.

We do still need to create a folder which will hold the published .mxd files (the files that the live AGS map services will point to).  I suggest here:
E:\\apps_data\\ago_publish\\published_mxd
...but if you have another preference that's fine with me.  **Can you create the "published_mxd" folder?**

The overall build-and-publish process will then work like this:
- build step: update existing .mxd files in E:\\apps_data\\ago_publish\\managed_mxd
- publish step: copy files from "managed_mxd" folder into "published_mxd" folder, then publish the service pointing to the "published_mxd" folder.

**Comment by bruce-tonkin** [comment]
@banders   Folder has been created: \\alpheratz.dmz\e$\apps_data\ago_publish\published.mxd

**Comment by banders** [comment]
@bruce-tonkin Can we call it "published_mxd" instead of "published.mxd"?  Then the folder name will be consistent with the adjacent folder "managed_mxd".

**Comment by bruce-tonkin** [comment]
Sorry typo: \\alpheratz.dmz\e$\apps_data\ago_publish\published_mxd

**Comment by banders** [comment]
Great. Thanks!

**Comment by bruce-tonkin** [comment]
Folder e;\temp has been deleted.
